# markdown: redcarpet

kramdown:
  input: GFM

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "tables", "superscript", "with_toc_data"]

highlight: pygments

html:
  class: no-js
# dir: rtl
  lang: en

# google_analytics: U-XXXXXX-XA

include: ['_patterns']
relative_permalinks: false

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

collections:
  patterns:
    output: true
    permalink: /pattern/:path/

sass:
  sass_dir: _sass
